### ISSUE TITLE
Handeling indentation

### ISSUE THREAD

**Issue by themsaid** [andreasindal/laravel-markdown#1]
Hello there,

Consider this:

```
<body>
    <div>
        <div>
        @markdown
            I'm not a **code**
        @endmarkdown
        </div>
    </div>
</body>
```

With the indentation before "I'm not a **code**", Parsedown will consider it a code block, I've made a fix for that https://github.com/themsaid/katana-core/blob/master/src/Markdown.php#L44

Was wondering if you handled the case in a better manner.

**Comment by alsterholm** [comment]
Hi @themsaid!

You're right, this might be a problem! I'll look into this when I get some time over to see if I could implement some sort of fix. Thank you!

**Comment by alsterholm** [comment]
Hi @themsaid!

Sorry it took so long (I guess better late than never? 💃). I took your advice and implemented your solution, and it seems to work great. I've given you credit both in the README and in the comment of the method.

Thank you!
