### ISSUE TITLE
ErrorException when using @markdown in my views

### ISSUE THREAD

**Issue by lucpotage** [andreasindal/laravel-markdown#12]
Hello!

I tried to use your package. I've followed the installation steps but unfortunately, when using the block-style syntax, I get the following error:

```
ErrorException in 4aa38964135806d6e004c7c84c51fa2583878528.php line 7:
Undefined property: Indal\Markdown\Parser::$parse (View: /var/www/laravel/resources/views/posts/LoremIpsum.blade.php)
```

When opening the mentioned view, the issue mentions this line:
`<?php echo app('Indal\Markdown\Parser')->parse; ?>`

Could you help me find what's going wrong? Thanks!

**Comment by lucpotage** [comment]
It seems that by replacing `!is_null($mardown)` with `!empty($markdown)` line 36 in the file `MarkdownServiceProvider.php`, it works. Any idea?

**Comment by lucpotage** [comment]
Actually, after further investigation, it seems you have not applied changes from branch **1.1** to branch **master**. Then when requiring the package via Composer, I get an older version…

**Comment by alsterholm** [comment]
Hi,

There was something wrong with the latest release. If you install via composer now, you should get the proper version. Thank you for reporting this, and I'm sorry for any inconvenience this may have caused you!
