### ISSUE TITLE
Expose line method

### ISSUE THREAD

**Issue by loranger** [andreasindal/laravel-markdown#14]
Hello,

It would be really great to being able to use the parsedown' `line` method directly from the facade, for some inliner use cases :

```php
{!! Markdown::line($markdown) !!}
```

Right now, the only way I found to format a string without wrapping paragraph is to call Parsedown directly, but I don't feel good with this... I'd really prefer to use the package I did install

```php
{!! Parsedown::instance()->line($markdown) !!}
```

Thank you so much

**Comment by alsterholm** [comment]
Hi!

This functionality was added in #15 and is avaiable in the 1.1.6 release.

Best regards

**Comment by loranger** [comment]
Awesome, thank you so much !
