### ISSUE TITLE
Link Target Blank

### ISSUE THREAD

**Issue by ajmerainfo** [andreasindal/laravel-markdown#17]
Hello,

How can we use target blank on each links?

**Comment by lucpotage** [comment]
Laravel Markdown is built upon a PHP parser. Maybe you should ask this question in the corresponding repo? I'm not sure there is any sustainable way to custom the parser from Laravel Markdown directly.
https://github.com/erusev/parsedown

**Comment by ajmerainfo** [comment]
@lucpotage Sure. Thank you.

**Comment by JCarlosR** [comment]
@ajmerainfo I see that you posted your question at the parsedown repo. However I am not sure how to use a different Parser from the `laravel-markdown` package.

I mean, where to store the new Parser class and modify the ServiceProvider. Do you create your own ServiceProvider and stopped using this package?

Please give me an idea. Thank you in advance.
