### ISSUE TITLE
Class for <code>

### ISSUE THREAD

**Issue by wondergitluda** [andreasindal/laravel-markdown#18]
Is it possible to implements @markdown on Blade passing it a class? Like for "code" tag, it could be the best highlights.js implementation.

**Comment by alsterholm** [comment]
Hi!

You can use GitHub flavored markdown to add a class to your code blocks, e.g.:

    ```php
    <?php
        $x = 10;
        // some php code
    ```

This example would add a class name of `language-php` to the code element. For further reference, please check out [Parsedown](https://github.com/erusev/parsedown) which Laravel-Markdown is built upon.

Best regards
