### ISSUE TITLE
No enter?

### ISSUE THREAD

**Issue by Sjoerd** [andreasindal/laravel-markdown#19]
Lines doesn't break.
```@markdown($topic->body)```
and
````
@markdown
{{ $topic->body }}
@endmarkdown
```

**Comment by alsterholm** [comment]
Hi!

The actual markdown parsing is done by the [Parsedown library](https://github.com/erusev/parsedown). To produce a line break, you need to end the line with two spaces. `<p>` tags are generated when there's a blank line separating two paragraphs (i.e. two newline characters).
