### ISSUE TITLE
Some things doesn't work

### ISSUE THREAD

**Issue by Sjoerd** [andreasindal/laravel-markdown#23]
Hello,
Some things doesn't work (for me?)

Making a list with bullets doesn't work, and the quote doesn't work as well.

> Quote
* Bullet
* List

**Comment by MikeMaldini** [comment]
Me Too ! Quote doesn't work 😭

**Comment by Sjoerd** [comment]
Somebody an alternative?

**Comment by alsterholm** [comment]
Hi!

This is likely a problem of the underlying Markdown parser used by default, which is [erusev/parsedown](https://github.com/erusev/parsedown).

If'd like, you can switch to a custom driver using the following method:

```php
app('Indal\Markdown\Parser')->setDriver($driver);
```

The `$driver` has to be an object that implements the `Indal\Markdown\Drivers\MarkdownDriver` interface.
