### ISSUE TITLE
Doesn't work properly with details and summary tags

### ISSUE THREAD

**Issue by pdrolima** [andreasindal/laravel-markdown#27]
Hello!

If markdown was added inside a `details` & `summary` tags will be interpreted as plain-text instead of the markdown as should be.

Is it possible to fix this?

Thank you!

**Comment by alsterholm** [comment]
Hi!

This is likely a problem of the underlying Markdown parser used by default, which is [erusev/parsedown](https://github.com/erusev/parsedown).

If'd like, you can switch to a custom driver using the following method:

```php
app('Indal\Markdown\Parser')->setDriver($driver);
```

The `$driver` has to be an object that implements the `Indal\Markdown\Drivers\MarkdownDriver` interface.
