### ISSUE TITLE
make compatible with ParsedownExtra

### ISSUE THREAD

**Issue by ghost** [andreasindal/laravel-markdown#4]
for extended usage of parsedown library this markdown wrapper should wrap ParsedownExtra library!

**Comment by alsterholm** [comment]
Hi,

Please see my response in #6 and I might consider it. Thank you!

Best regards

**Comment by alsterholm** [comment]
Closing due to ParsedownExtra failing checks on TravisCI as pointed out by @lntn in #6.

**Comment by ghost** [comment]
thanks for your attention!
